### ISSUE TITLE
Set up pipeline for github

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/warmup-exercise-team-1#1]
In github, setup a pipeline for code commits, where
- no one is able to commit directly to main
- everyone creates (well-named) branches, and raises a pull request which needs to be _reviewed_ and _approved_ before pushing to main.

**Comment by danwyl** [comment]
Currently have main and dev branches set up, requiring a PR without review into dev, and a PR into main with 3 approvals on the code review.

**Comment by ravishende** [comment]
I think we should be good to close it then. Unless there was something else you were trying to set up?

**Comment by danwyl** [comment]
Added it so a single PR is required to merge into dev, which should be more consistent with practices of the class.
