### ISSUE TITLE
Add Hover functionality

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/warmup-exercise-team-1#10]
When an option is hovered over, Either:
  - Give it a new color border
  - Change the color of it to be slightly darker/lighter

**Comment by ravishende** [comment]
This is difficult due to the fact that images are rectangles. If you switch over to the branch `style-radio-buttons`, you can see  a basic prototype of what the options look like. With a box-shadow hover on the container, it looks out of place. This is because the container that wraps the radio button, image, and label is a rectangle, while the visual part of the image is a piece of an arch. The professor found a work around for this, as described in the lecture where he demoed the sentiment rating widget chatgpt made.

**Comment by ravishende** [comment]
In pull request #15, there are a few experimental lines that seem to cover this for the most part. It works for when it is hovered, focused (keyboards), and selected. All that is left is to fine tune these and potentially add a background to it which could be harder as described in the above comment.

Here are the stylings:
```
/* show which radio button is focused (useful for keyboard based selection) */
.rating-option:focus + label {
    filter: brightness(120%);
}
/* show which radio button is selected (clicked on) */
.rating-option:checked + label {
    filter: brightness(80%);
}
/* show which radio button is hovered over by mouse */
.rating-img:hover {
    filter: brightness(120%);
}

```

**Comment by BenjiRyujin** [comment]
Currently working around an animated slide out with CSS transform, but the experimental styling is a good base to start out with.
