### ISSUE TITLE
Allow tab navigation through widget

### ISSUE THREAD

**Issue by BenjiRyujin** [cse110-sp24-group23/warmup-exercise-team-1#21]
Let the widget user select through the different sentiment options simply by clicking tab + enter. Currently the flow only goes to the first rating-option and then to the submit button.

**Comment by ravishende** [comment]
With radio buttons, you use arrow keys rather than tabs, so you tab to the first one, then use arrow keys to get to the next ones. I'm pretty sure this is the case with most sites, but I'm not positive on that.

**Comment by BenjiRyujin** [comment]
> With radio buttons, you use arrow keys rather than tabs, so you tab to the first one, then use arrow keys to get to the next ones. I'm pretty sure this is the case with most sites, but I'm not positive on that.

Oh, thank you I didn't know this. I'll close the issue.
