### ISSUE TITLE
Write docs (wiki)

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/warmup-exercise-team-1#4]
Look into github wiki docs and write thorough documentation for users of this app.

**Comment by danwyl** [comment]
Added basic getting-started

**Comment by danwyl** [comment]
Added Motivations and Features to Main Page

**Comment by danwyl** [comment]
Added Footer / Sidebar. 
Can be found here:
https://github.com/cse110-sp24-group23/warmup-exercise-team-1/wiki

**Comment by danwyl** [comment]
Putting this into test for now, just need developer OK and I can close this (we don't need to merge anything)
