### ISSUE TITLE
Style radio buttons as visuals

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/warmup-exercise-team-1#5]
1. get them in the same line
2. get them to work with images - you can use placeholder images until finalized images are done (#3)

**Comment by BenjiRyujin** [comment]
I think a flexbox should work to organize the elements in a row.

**Comment by ravishende** [comment]
yep, I've got a prototype for it working, just waiting on the photos to actually update it. I didn't actually need to do anything for step 1 since that's their default.
