### ISSUE TITLE
Come up with and implement tests

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/warmup-exercise-team-1#8]
1. Test good (normal) conditions
2. Test w/ bad wifi
3. Test w/ no JS
4. test w/ no CSS
5. Test selecting different emotions several times before submitting
6. Test many browsers
        - Safari, Firefox, Chrome, Edge, etc.
7. Think of and implement more tests

**Comment by danwyl** [comment]
Don't know why this didn't get closed with the PR, but closing now
